### ISSUE TITLE
Flashing board

### ISSUE THREAD

**Issue by Shocka-Zulu** [terrafirma2021/ESP32s3_KMBOX#4] opened 2024-08-11 16:57 UTC
Good afternoon, firs time with an esp32 board, I've got vs-code and the ide setup build runs fine but i get a chip stops responding error when attempting to flash

Auto-detected: COM21
Uploading .pio\build\esp32-s3-n16r8\firmware.bin
esptool.py v4.5.1
Serial port COM21
Connecting.....
Chip is ESP32-S3 (revision v0.2)
Features: WiFi, BLE
Crystal is 40MHz
MAC: 3c:84:27:ca:7e:dc
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...

Traceback (most recent call last):
  File "\.platformio\packages\tool-esptoolpy\esptool\__init__.py", line 1032, in _main
    main()
  File "\.platformio\packages\tool-esptoolpy\esptool\__init__.py", line 816, in main
    esp.flash_set_parameters(flash_size_bytes(args.flash_size))
  File "\.platformio\packages\tool-esptoolpy\esptool\loader.py", line 1184, in flash_set_parameters
    self.check_command(
  File "\.platformio\packages\tool-esptoolpy\esptool\loader.py", line 435, in check_command
    val, data = self.command(op, data, chk, timeout=timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.platformio\packages\tool-esptoolpy\esptool\loader.py", line 404, in command
    p = self.read()
        ^^^^^^^^^^^
  File "\.platformio\packages\tool-esptoolpy\esptool\loader.py", line 337, in read
    return next(self._slip_reader)
           ^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

A fatal error occurred: The chip stopped responding.
*** [upload] Error 2

any guidance would be appreciated

**Comment by terrafirma2021** [comment] 2024-08-26 20:15
HI sorry for getting back to you late,

the issue is your psram config on your board.

Please check the specs of your dev kit, 


my code was designed for the n16 r8 variant of the dev kit and you may need to make changes,

its reported by the 
esp.flash_set_parameters(flash_size_bytes(args.flash_size))


If you use the esptool.py flash_id


it will tell you,



you can then make changes to the board to match 


good luck with your project

**Comment by terrafirma2021** [comment] 2024-08-26 20:16
Closing this issue now with your fix, if you get stuck further then please feel free to reopen .


cheers

**Closed as completed by terrafirma2021** 2024-08-26 20:16 UTC
